### PR TITLE
Add Club Counter

### PR DESCRIPTION
**Pull request by Incompleteusern**
Adds a basic max club count to the conclusion

image

### CODE REVIEW

**Comment by vEnhance** [comment]
So annoyingly this doesn't handle "inline" problems that don't have a PUID. I thought I could work around it by injecting the `\addtocounter` directly but that didn't work either for probably above-my-paygrade LaTeX rasons.

I'll just manually tamper the counter I guess for those edge cases.

**Comment by Incompleteusern** [comment]
What are inline problems?

**Comment by vEnhance** [comment]
> What are inline problems?

stuff like
```latex
\begin{probZ}\addtocounter{clubcounter}{9}
  Clear any 42 levels of the game
  \href{https://en.wikipedia.org/wiki/Baba_Is_You}{Baba is You}
  that you haven't already.

  The game is available at \url{https://hempuli.itch.io/baba}.
  (It costs about \$15;
  if this presents a financial hardship to you,
  I can just buy you a copy, let me know.)
\end{probZ}
```

anything that doesn't have a PUID

**Comment by Incompleteusern** [comment]
oh

**Pull request merged**
